{% set name = "POPSregression" %}
{% set version = "0.3.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/popsregression-{{ version }}.tar.gz
  sha256: d15d29480dac4f582988e9f3a14453ae8e98d365d838c0a82ecc11ea7fe7b39d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - scikit-learn >=1.6.1
    - scipy >=1.6.0
    - numpy >=1.20.0

test:
  imports:
    - POPSRegression
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tomswinburne/POPS-Regression
  summary: Bayesian regression for low-noise data using POPS algorithm
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tomswinburne
    - jan-janssen
