{% set name = "POPSregression" %}
{% set version = "0.3.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/popsregression-{{ version }}.tar.gz
  sha256: f1d8fbb7a61b80d775ad0615c7ddb99abb39888523ce43c2ced82962d38c5fec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - scikit-learn >=0.24.0
    - scipy >=1.6.0
    - numpy >=1.20.0

test:
  imports:
    - POPSRegression
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tomswinburne/POPS-Regression
  summary: Bayesian regression for low-noise data using POPS algorithm
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tomswinburne
    - jan-janssen
