schema_version: 1

context:
  name: POPSregression
  version: "0.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/popsregression-${{ version }}.tar.gz
  sha256: 4f99efd1a0a58b83729b7b2817612db832012040895314a539af65fcba426f7c

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=45
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - scikit-learn >=1.6.1
    - scipy >=1.6.0
    - numpy >=1.20.0

tests:
  - python:
      imports:
        - POPSRegression
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Bayesian regression for low-noise data using POPS algorithm
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tomswinburne/POPS-Regression

extra:
  recipe-maintainers:
    - tomswinburne
    - jan-janssen
